name: Checkstyle

on: [pull_request, push]

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    name: Checkstyle
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:
          fail_on_error: true
          reporter: 'github-pr-check'
          tool_name: 'checkstyle'
          level: error
          filter_mode: nofilter
          checkstyle_config: checkstyle.xml
          checkstyle_version: 9.0.1